server:
  port: 8003
mybatis:
  # mybatis配置文件所在路径
  config-location: classpath:mybatis/mybatis.cfg.xml
  # 所有entity别名类所在包，api工程里的
  type-aliases-package: com.hae502.springcloud.entity
  mapper-locations:
  # mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: microservicecloud-dept
  datasource:
    # 数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动
    driver-class-name: org.gjt.mm.mysql.Driver
    # 数据库名称
    url: jdbc:mysql://localhost:3306/clouddb03?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: root
    dbcp2:
      # 数据库连接池的最小维持连接数
      min-idle: 5
      # 初始化连接数
      initial-size: 5
      # 最大连接数
      max-total: 5
      # 等待连接获取的最大超时时间
      max-wait-millis: 200
      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除. 注意: 设置为true后如果要生效,
      # validationQuery参数必须设置为非空字符串
      test-while-idle: true
      # SQL查询,用来验证从连接池取出的连接,在将连接返回给调用者之前.如果指定,则查询必须是一个SQL SELECT并且必须返回至少一行记录
      validation-query: 'SELECT 1'
      # 指明是否在从池中取出连接前进行检验,如果检验失败, 则从池中去除连接并尝试取出另一个，注意: 设置为true后如果要生效,
      # validationQuery参数必须设置为非空字符串
      test-on-borrow: false
      # 指明是否在归还到池中前进行检验，注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
      test-on-return: false
      pool-prepared-statements: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: microservicecloud-dept8003
    prefer-ip-address: true
info:
  app.name: hae502-mimicroservicecloud
  company.name: www.hae502.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}